In [2]:
import numpy as np


In [11]:
val=np.array([4,9,16])  #NumPy applies mathematical operations element-wise (to each element individually).
print(val)

[ 4  9 16]


In [12]:
val= val + 1
print(val)

[ 5 10 17]


In [13]:
val= val-1
print(val)

[ 4  9 16]


In [14]:
#wap to multiply 5 to all the elements

val= val*5
print(val)

[20 45 80]
