install a library


In [1]:
!pip install numpy #this is how we install a library we already have it installed in collab.

import that library #step2


In [3]:
import numpy as np
print(numpy.__version__)

2.0.2


In [4]:
#how to create an array
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
#or
l=[1,2,3,4]
arr=np.array(l)
print(l)

[1, 2, 3, 4]


In [6]:
type(arr)

numpy.ndarray

In [11]:
arr2=np.arange(1, 10, 2 )     #same as the range() function #second wy of making array
print(arr2)

[1 3 5 7 9]


In [12]:
#third way of making array

arr3=np.linspace(0,1,5)   #give a range, and get the elements you need.
print(arr3)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
type(arr3)   #nd stands for n dimensional

numpy.ndarray

In [15]:
arr.shape   #its showing 4 because we just have 4 elements that is 1,2,3,4

(4,)

In [16]:
arr.ndim #Because it is a 1D array — just one row/list of values.

1

In [18]:
#creating array as the name of zero
#here 3,3 represents number of rows, number of elements. if we change it and just keep one value for example ((1)) it will be number of elements.
zero=np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
zero.shape #this tells how many dimensions

(3, 3)

In [24]:
one=np.ones((10,10))  #creating array one with 10x10
print(one)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [25]:
eye=np.eye(2)
print(eye)

[[1. 0.]
 [0. 1.]]


In [8]:
import numpy as np
#reshaping array
arr= np.arange(6)
print(arr)


[0 1 2 3 4 5]


In [13]:
r = arr.reshape(2,3)
print(r)

[[0 1 2]
 [3 4 5]]


In [14]:
#to check dimensions , size, shape you can use ndim , shape size

r.ndim

2